project:
  type: website

website:
  title: "GESIS"
  favicon: logos/favicon.ico
  navbar:
    title: false
    logo: logos/logo_gesis_en.png
    favicon: 
    logo-alt: "GESIS logo."
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: |
      **Standort Mannheim**  
      GESIS - Leibniz-Institut für Sozialwissenschaften  
      B6, 4-5  
      68159 Mannheim  
      Telefon: +49-(0)621-1246-0  
      Fax: +49-(0)621-1246-100
    center: |
      **Standort Köln**  
      GESIS - Leibniz-Institut für Sozialwissenschaften  
      Unter Sachsenhausen 6-8  
      50667 Köln  
      Telefon: +49-(0)221-47694-0  
      Fax: +49-(0)221-47694-199

    right: |
      ![GESIS ist ein Institut der Leibniz-Gemeinschaft](logos/leibniz_logo_en_white.svg)  
      Impressum Datenschutz

format:
  html:
    theme: [gesis-theme.scss,cerulean]
    css: styles.css
    fontsize: 1rem
    linestretch: 1.6
    title-block-banner: logos/microsite.png
    title-block-banner-color: '#fff'
    anchor-sections: false
    smooth-scrolling: true
    toc: true
    toc-title: " "